// @vitest-environment jsdom
//
// Feature: premium-ui-redesign — Phase 3 verification.
//
// Property 13 — Urgency, status, and error indicators always combine
// color with text or icon.
// Validates: Requirements 11.7
//
// Requirement 11.7 — "THE redesigned color tokens SHALL NOT use color as
// the sole indicator of urgency, status, or error — a text label AND/OR
// an iconographic mark SHALL always also be present, as enforced by the
// existing UrgencyBadge pattern."
//
// ---------------------------------------------------------------------------
// Strategy
// ---------------------------------------------------------------------------
// For every receipt generated by `arbReceipt()`, render `<UrgencyBadge>`
// with the receipt's `urgency` / `days_remaining` / `status` fields, then
// walk the rendered DOM. For every element whose `class` attribute carries
// a semantic color utility (`text-accent` / `text-success` / `text-warning`
// / `text-danger`, or the matching `border-*` / `bg-*-tint` siblings) we
// assert that the element ALSO carries a non-whitespace text label OR an
// `<svg>` icon descendant. The "color alone" failure mode — a colored
// chip with empty content — is the precise shape Requirement 11.7
// forbids.
//
// The test exercises the same property from a second angle: it renders
// the redesigned `<Badge>` primitive directly across each semantic
// variant (`success`, `warning`, `danger`, `default`) and verifies the
// `color + (text OR icon)` contract holds at the primitive layer too.
// The receipt-dashboard hero summary chips (`due soon`, `All calm`) and
// any future status-bearing call site reach this property through the
// same primitive.
//
// ---------------------------------------------------------------------------

import { createElement } from "react";

import { cleanup, render } from "@testing-library/react";
import fc from "fast-check";
import { afterEach, describe, expect, it } from "vitest";

import { Badge } from "@/components/ui/badge";
import { UrgencyBadge } from "@/components/receipts/urgency-badge";
import { arbReceipt } from "./_arbitraries";

// ---------------------------------------------------------------------------
// Semantic color-class detection
// ---------------------------------------------------------------------------

/**
 * Tailwind utilities that mark an element as a color-coded urgency / status
 * / error indicator on a redesigned surface. The four semantic tokens
 * (`accent`, `success`, `warning`, `danger`) cover every variant emitted
 * by the redesigned `<Badge>` primitive:
 *
 *   - default → `border-border bg-accent-tint text-accent`
 *   - success → `border-success bg-surface text-success`
 *   - warning → `border-warning bg-surface text-warning`
 *   - danger  → `border-danger  bg-surface text-danger`
 *
 * `bg-accent-tint` is included so the default chip — used for non-active
 * receipt status (`returned`, `kept`, `expired`) — is treated as a
 * color-coded indicator too.
 */
const SEMANTIC_COLOR_CLASS_RE =
  /\b(?:text|border|bg)-(?:accent|success|warning|danger)(?:-tint)?\b/;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

afterEach(() => cleanup());

function classOf(el: Element): string {
  return el.getAttribute("class") ?? "";
}

function isColorCoded(el: Element): boolean {
  return SEMANTIC_COLOR_CLASS_RE.test(classOf(el));
}

function hasNonWhitespaceText(el: Element): boolean {
  return (el.textContent ?? "").trim().length > 0;
}

function hasIconDescendant(el: Element): boolean {
  // An `<svg>` anywhere under `el` (the element itself does not count —
  // we want a descendant icon, since the color-coded element itself is
  // typically the chip wrapper, not the icon).
  return el.querySelector("svg") !== null;
}

function colorCodedDescendants(root: ParentNode): Element[] {
  const out: Element[] = [];
  // The root itself if it is an Element with a semantic color class.
  if ("getAttribute" in root && isColorCoded(root as Element)) {
    out.push(root as Element);
  }
  for (const el of root.querySelectorAll("*")) {
    if (isColorCoded(el)) out.push(el);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("Property 13 — urgency / status indicators combine color with text or icon (Requirement 11.7)", () => {
  it("for every generated receipt, <UrgencyBadge> renders at least one color-coded element and each one carries text or an icon", () => {
    fc.assert(
      fc.property(arbReceipt(), (receipt) => {
        const { container } = render(
          createElement(UrgencyBadge, {
            urgency: receipt.urgency,
            daysRemaining: receipt.days_remaining,
            status: receipt.status,
          }),
        );

        const colorEls = colorCodedDescendants(container);

        // Sanity: <UrgencyBadge> always wraps its content in a semantic
        // <Badge>. If no color-coded element is found, the redesigned
        // Badge has drifted away from semantic-color utilities and the
        // property cannot be evaluated meaningfully.
        if (colorEls.length === 0) {
          throw new Error(
            `<UrgencyBadge> rendered no color-coded element for receipt ` +
              `(urgency=${receipt.urgency}, daysRemaining=${receipt.days_remaining}, status=${receipt.status}). ` +
              `Property 13 expects at least one semantic color class on the badge.`,
          );
        }

        for (const el of colorEls) {
          const hasText = hasNonWhitespaceText(el);
          const hasIcon = hasIconDescendant(el);
          if (!hasText && !hasIcon) {
            throw new Error(
              `Color-coded element relies on color alone (Requirement 11.7 violation). ` +
                `class="${classOf(el)}", outerHTML=${el.outerHTML.slice(0, 240)}. ` +
                `Receipt: urgency=${receipt.urgency}, daysRemaining=${receipt.days_remaining}, status=${receipt.status}.`,
            );
          }
        }

        cleanup();
        return true;
      }),
      // High enough to sample every (urgency × bucket(daysRemaining) ×
      // status) combination at least once in expectation.
      { numRuns: 64 },
    );
  });

  it("every <Badge> semantic variant renders a color-coded surface whose content satisfies the property", () => {
    // The semantic <Badge> variants are the redesigned primitive's
    // mechanism for urgency / status / error indicators. Render each
    // variant with a representative content (icon + text) and verify the
    // `color + (text OR icon)` contract holds at the primitive layer
    // too. fast-check enumerates the 4 variants on each run.
    const variants = ["default", "success", "warning", "danger"] as const;

    fc.assert(
      fc.property(fc.constantFrom(...variants), (variant) => {
        const { container } = render(
          createElement(
            Badge,
            { variant },
            createElement(
              "svg",
              {
                "aria-hidden": "true",
                "data-test-icon": "true",
                width: 12,
                height: 12,
              },
              createElement("circle", { cx: 6, cy: 6, r: 3 }),
            ),
            createElement(
              "span",
              { "data-test-label": "true" },
              variant,
            ),
          ),
        );

        const colorEls = colorCodedDescendants(container);
        expect(
          colorEls.length,
          `Badge variant="${variant}" rendered no semantic color class — ` +
            `the redesigned variant→class mapping has drifted.`,
        ).toBeGreaterThan(0);

        for (const el of colorEls) {
          const hasText = hasNonWhitespaceText(el);
          const hasIcon = hasIconDescendant(el);
          expect(
            hasText || hasIcon,
            `Badge variant="${variant}" produced a color-coded element ` +
              `with neither text nor an icon: class="${classOf(el)}".`,
          ).toBe(true);
        }

        cleanup();
        return true;
      }),
      { numRuns: 16 },
    );
  });

  it("a Badge rendered with empty children would violate the property (negative control)", () => {
    // Documents the failure mode the property catches: an explicitly
    // color-coded element with no text and no icon is the exact shape
    // Requirement 11.7 forbids. We render that shape directly and
    // confirm the detector flags it. This is a guard against the
    // assertion logic above silently passing on a buggy implementation.
    const { container } = render(
      createElement(Badge, { variant: "danger" }),
    );

    const colorEls = colorCodedDescendants(container);
    expect(colorEls.length).toBeGreaterThan(0);

    const offender = colorEls.find(
      (el) => !hasNonWhitespaceText(el) && !hasIconDescendant(el),
    );
    expect(
      offender,
      "Negative control: an empty color-coded Badge should be detected as " +
        "the failure mode Requirement 11.7 forbids.",
    ).toBeDefined();
  });
});
